### ISSUE TITLE
Spacing of UI elements

### ISSUE THREAD

**Issue by con-f-use** [LordBlick/kicadPanelizer#3]
The UI elements such as buttons and labels have incorrect spacings with some implementations of GTK. The UI should use relative spacing as opposed to absolute. Here a screenshot from a Debian system (mind the cutoff button text and labels saying "Clear log vi" and "Margi"):

![UI spacing problem](http://i.imgur.com/rE3b1Gi.png)

**Comment by LordBlick** [comment]
Use narrow font http://ttfonts.net/font/40323_UniversCondensed.htm

**Comment by con-f-use** [comment]
Or you could make the window a little bigger and the elements scale, as would be good practise...

**Comment by con-f-use** [comment]
:-<

**Comment by LordBlick** [comment]
It will be fixed after migrate to gtk3, for now it's in maintain mode
