### ISSUE TITLE
Feature request: Mechanical conncetion between boards of a panel

### ISSUE THREAD

**Issue by con-f-use** [LordBlick/kicadPanelizer#4]
Sometimes a break-away connection between the individual boars in a panel is required. The current version only offers continuous edges. An option to break the inner edges would be useful. Here is an example of what I mean:

![Break-away edge-cuts](http://i.imgur.com/WLsoJbS.png)

**Comment by LordBlick** [comment]
Application is on way to change config file format,  introduce X/Y space definition and fiducials on margins. When I find some time, I will do it.

**Comment by skorokithakis** [comment]
You can do this "easily" now by making a board that includes the mechanical connection on the bottom and a "break" on the edge cuts at the top, and set margins to 0, so it tiles correctly. You still need to fix the edges, though.

The panelizer is an extremely useful program, if it had this feature it would have been perfect.

P.S. I actually edited the source code to prevent it from adding edge cuts (so my solution would work), but I don't remember which lines I commented out. If you want, let me know and I'll try to find them again. Would be fantastic if this feature could be implemented, though.

**Comment by LordBlick** [comment]
Added to TO DO section of README.md
