### ISSUE TITLE
execute  uipanelize.py using a normal python installation

### ISSUE THREAD

**Issue by ihouses** [LordBlick/kicadPanelizer#5]
Hello,

I am trying to execute the script  uipanelize.py using my normal python 2.7 32 bit installation. But I can not import _pcbnew DLL. I copied some files from Kicad python installation to the normal python 2.7 library but... it doens't work.

What I am doing wrong?

Thanks!

**Comment by LordBlick** [comment]
Check python path
`python -c "import sys; print (sys.path)"`
