### ISSUE TITLE
something went wrong...

### ISSUE THREAD

**Issue by macsimski** [LordBlick/kicadPanelizer#6]
Error message:
	Wrong number or type of arguments for overloaded function 'MODULE_Duplicate'.
  Possible C/C++ prototypes are:
    MODULE::Duplicate(BOARD_ITEM const *,bool,bool)
    MODULE::Duplicate(BOARD_ITEM const *,bool)

kicad version from help menu:

Application: kicad
Version: no-vcs-found-799c8b6~57~ubuntu14.04.1, release build
Libraries: wxWidgets 3.0.2
           libcurl/7.35.0 OpenSSL/1.0.1f zlib/1.2.8 libidn/1.28 librtmp/2.3
Platform: Linux 3.13.0-105-generic x86_64, 64 bit, Little endian, wxGTK
- Build Info -
wxWidgets: 3.0.2 (wchar_t,wx containers,compatible with 2.8)
Boost: 1.54.0
Curl: 7.35.0
KiCad - Compiler: GCC 4.8.4 with C++ ABI 1002
        Settings: USE_WX_GRAPHICS_CONTEXT=OFF
                  USE_WX_OVERLAY=OFF
                  KICAD_SCRIPTING=ON
                  KICAD_SCRIPTING_MODULES=ON
                  KICAD_SCRIPTING_WXPYTHON=ON
                  KICAD_SCRIPTING_ACTION_MENU=OFF
                  BUILD_GITHUB_PLUGIN=ON
                  KICAD_USE_OCE=ON

**Comment by LordBlick** [comment]
At the moment no idea, got very long break, sad true life…

**Comment by LordBlick** [comment]
Fixed now. Probably… No feedback in over year.

**Comment by macsimski** [comment]
Ha. will look into it when i have some spare time next week. thanks!
