### ISSUE TITLE
Add project to Code Shelter?

### ISSUE THREAD

**Issue by skorokithakis** [LordBlick/kicadPanelizer#7]
Hello! I use this project a lot and have fixed some issues I found with panelizing (mainly removing edges so I can add mousebites). Would you be able to add this project to [the Code Shelter](https://www.codeshelter.co/) so we can help maintain it? Or is this actively maintained and it would be fine if I submitted my patches in a PR?

Thanks!

**Comment by LordBlick** [comment]
Can you use pull request?

**Comment by skorokithakis** [comment]
I can, but judging by the response time, I think it might be better if the project was in code shelter. It's up to you, though.

**Comment by LordBlick** [comment]
Now I've updated my email filters to separate this project messages from other, so I promise to short my response time. Feel free to make pull request. It's hard to me to maintain another programistic tool.

**Comment by skorokithakis** [comment]
Ah, okay, will do. You don't have to maintain anything with Code Shelter, though, you press a button and other people maintain the project for you.

**Comment by LordBlick** [comment]
OK, nice to know. Beside of this I've got my ideas to develop and a perfectistic habit of keeping order in the code, so I would prefer to just raw git. More tools, more probably lack of security.
