### ISSUE TITLE
Duplicate() error

### ISSUE THREAD

**Issue by Gasman2014** [LordBlick/kicadPanelizer#8]
Had this starred for a while but prompted to try it agin following recent update. have now got this running on macOS by changing the top lines to;

```
#!/Applications/Kicad/kicad.app/Contents/Applications/pcbnew.app/Contents/MacOS/Python
  2 # -*- encoding: utf-8 -*-
  3 # -*- coding: utf-8 -*-
  4
  5 import sys
  6 sys.path.insert(0, "/Applications/Kicad/kicad.app/Contents/Frameworks/python/site-packages/")
  7 import pcbnew

```
However, am hitting a problem reading a current pcb file (from Kicad 5.0.2)

```Reading file:
	'~/EDA_Workspace/Projects/PostBox/PostBox.kicad_pcb'
Script Version: v.0.86. Error report:
Something went wrong. Contact developers.
Provide info about current configuration and processed file:
	'~/EDA_Workspace/Projects/PostBox/PostBox.kicad_pcb'
Error message:
	Duplicate() takes exactly 1 argument (2 given)
```

![screen shot 2019-02-18 at 13 05 52](https://user-images.githubusercontent.com/8401593/52952958-0c7e2400-337e-11e9-8232-eff33329ebb9.png)

**Comment by LordBlick** [comment]
Try now

**Comment by LordBlick** [comment]
I do not have any idea about MacOS system paths. `#!/usr/bin/env python2` is standard header. It's possible, that you can fix it with tune up your system configuration and proper Python KiCAD installation. KiCAD should add own plugin path to Python run path. Python during installation should add own path to system  environment.
