### ISSUE TITLE
Alternative fallback font

### ISSUE THREAD

**Issue by Gasman2014** [LordBlick/kicadPanelizer#9]
Any possibility of a more widely available fallback font or do I need another package? [macOS]

/Applications/Kicad/kicad.app/Contents/Frameworks/Python.framework/Versions/Current/bin/python pcbPanelize
/Users/johnpateman/Kicad/kicadPanelizer/uiPanelize.py:211: PangoWarning: couldn't load font "Univers,Sans Condensed Not-Rotated 8", modified variant/weight/stretch as fallback, expect ugly output.
  pangoTxtSpc = pangoLayout.get_pixel_size()[0]

**Comment by LordBlick** [comment]
Install this font http://ttfonts.net/font/40323_UniversCondensed.htm

**Comment by LordBlick** [comment]
Added info about in README.md, closing.
